<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Days_Dropdown</name>
   <tag></tag>
   <elementGuidId>ce386398-da1f-4e2a-9267-c410a96151f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-demo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select-demo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5c2ee6d7-dd21-4a33-bc81-988daa99a3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e990ea19-2df0-470c-ac74-16da06006804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-demo</value>
      <webElementGuid>1c57e38a-bb90-4885-be71-164f1e3142e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				Please select
				 Sunday
				  Monday
				  Tuesday
				  Wednesday
				  Thursday
				  Friday
				  Saturday
			  </value>
      <webElementGuid>67ddb413-3dec-4663-937b-2aef916b66af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-demo&quot;)</value>
      <webElementGuid>8182538f-68ae-4d64-8592-51ca3a515063</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select-demo']</value>
      <webElementGuid>eff14a12-1988-4a1d-b41f-acca99773116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='easycont']/div/div[2]/div/div[2]/select</value>
      <webElementGuid>f5c28c11-5d7d-4618-834a-cf7e2ebced35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a day (select one):'])[1]/following::select[1]</value>
      <webElementGuid>fe82c022-b068-4d57-a10e-6cf0b0e07768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select List Demo'])[1]/following::select[1]</value>
      <webElementGuid>ae7fa19a-3574-4525-9329-0b5dbb24193c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi Select List Demo'])[1]/preceding::select[1]</value>
      <webElementGuid>e79b3ad5-c734-4cc5-b0ae-03de30c61449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Selected'])[1]/preceding::select[2]</value>
      <webElementGuid>f25d061e-fbea-4a5a-8d95-c6bcc57af112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>8d23a6a3-2c9a-4df1-abdf-666451d59e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'select-demo' and (text() = '
				Please select
				 Sunday
				  Monday
				  Tuesday
				  Wednesday
				  Thursday
				  Friday
				  Saturday
			  ' or . = '
				Please select
				 Sunday
				  Monday
				  Tuesday
				  Wednesday
				  Thursday
				  Friday
				  Saturday
			  ')]</value>
      <webElementGuid>ba8eafa0-70ac-4c46-a72a-22dd8e414a0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
