<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>English</name>
   <tag></tag>
   <elementGuidId>cfda8429-ba05-4842-aa64-c33af4977ac8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SIvCob']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SIvCob > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ba140cb1-4ef9-48ea-aa9a-2c64848f8ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.co.in/setprefs?sig=0_PtUmYSVLPyO6EDJaH3xIsdTdCxY%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwj7l8zTvpuEAxXMTmwGHQ6nCe0Q2ZgBCBQ</value>
      <webElementGuid>cc277826-6224-4dc6-b17b-96a31e37d4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>a3d02c17-1cdd-4be2-b9b2-c02e5bd16af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SIvCob&quot;)/a[1]</value>
      <webElementGuid>b3c65451-368c-4d15-8ea3-b91c276087ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SIvCob']/a</value>
      <webElementGuid>140fad29-f222-49f7-b1d8-9a7dfbf2ff05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'English')]</value>
      <webElementGuid>e80d76b9-6d5f-441c-b298-d40e6283a8dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='பொருத்தமற்ற முன்கணிப்புகளைப் புகாரளி'])[1]/following::a[1]</value>
      <webElementGuid>bd1b1e30-955f-477a-945d-eecf7f662e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='हिन्दी'])[1]/preceding::a[1]</value>
      <webElementGuid>26d5bd88-b2ec-4486-99d2-408557c41be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='বাংলা'])[1]/preceding::a[2]</value>
      <webElementGuid>33b06e7d-3fdb-4d5d-aa5c-b9b540572fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='English']/parent::*</value>
      <webElementGuid>dc58529e-5bf8-487f-a9bd-804b46e2cf95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.co.in/setprefs?sig=0_PtUmYSVLPyO6EDJaH3xIsdTdCxY%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwj7l8zTvpuEAxXMTmwGHQ6nCe0Q2ZgBCBQ')]</value>
      <webElementGuid>76c23c08-8b7c-45a8-a8b1-3193c28bd428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a</value>
      <webElementGuid>4585ea3f-9ad0-4b7f-82e3-50adb264cffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.co.in/setprefs?sig=0_PtUmYSVLPyO6EDJaH3xIsdTdCxY%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwj7l8zTvpuEAxXMTmwGHQ6nCe0Q2ZgBCBQ' and (text() = 'English' or . = 'English')]</value>
      <webElementGuid>64cfa2b4-9e52-45e6-bab4-7b4b3f89cb27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
