<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tamil</name>
   <tag></tag>
   <elementGuidId>442ce100-6b3a-4be3-bf89-47fd7b175481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SIvCob']/a[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(5)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aea811a5-bcfc-4e24-b5a9-8b92918d39a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.co.in/setprefs?sig=0_PtUmYSVLPyO6EDJaH3xIsdTdCxY%3D&amp;hl=ta&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjXvLvEvpuEAxUFa2wGHatTAT4Q2ZgBCBg</value>
      <webElementGuid>01867104-e06f-4026-a943-68ee8772e2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>தமிழ்</value>
      <webElementGuid>6bb3e41a-365b-48de-a919-991d121eca60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SIvCob&quot;)/a[5]</value>
      <webElementGuid>1d0c88d8-89c4-4f7d-b64d-05b644560115</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SIvCob']/a[5]</value>
      <webElementGuid>68ba5a95-1e77-4665-a529-8d19427abf44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'தமிழ்')]</value>
      <webElementGuid>0860e33b-01d2-4d56-bb23-bcc406495e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='मराठी'])[1]/following::a[1]</value>
      <webElementGuid>82db9337-b82e-4255-9832-e4420df8ab6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='తెలుగు'])[1]/following::a[2]</value>
      <webElementGuid>6a53d41e-5485-406e-8e83-4269ff27002d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ગુજરાતી'])[1]/preceding::a[1]</value>
      <webElementGuid>e442235e-f932-4455-9c9b-18b65f8d0d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ಕನ್ನಡ'])[1]/preceding::a[2]</value>
      <webElementGuid>701a4c7d-4dfa-4386-ab16-a093913f5c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='தமிழ்']/parent::*</value>
      <webElementGuid>d4ae83c4-da13-48c2-89fc-36d3d476fecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.co.in/setprefs?sig=0_PtUmYSVLPyO6EDJaH3xIsdTdCxY%3D&amp;hl=ta&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjXvLvEvpuEAxUFa2wGHatTAT4Q2ZgBCBg')]</value>
      <webElementGuid>29044923-720a-47cd-8a27-21ce80b13baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>6a02e890-d4e8-4599-820d-1b6eda14e43d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.co.in/setprefs?sig=0_PtUmYSVLPyO6EDJaH3xIsdTdCxY%3D&amp;hl=ta&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjXvLvEvpuEAxUFa2wGHatTAT4Q2ZgBCBg' and (text() = 'தமிழ்' or . = 'தமிழ்')]</value>
      <webElementGuid>449c1bd9-61de-46dc-823b-4879d56170c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
