<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>ad8dee05-925d-494b-9476-c526d01d4e83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SIvCob']/a[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(5)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>abb088a2-ad8e-4016-88ed-0b573af58b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.co.in/setprefs?sig=0_limky8E0i7HQ_0Klma2ehAgaS6I%3D&amp;hl=ta&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjwms7quZuEAxWUqFYBHc6xAeIQ2ZgBCBg</value>
      <webElementGuid>c38b5956-cbb5-48be-885a-e7e2803a0561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>தமிழ்</value>
      <webElementGuid>f7e0a9e2-5d8c-4bba-90ed-996153d6b248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SIvCob&quot;)/a[5]</value>
      <webElementGuid>76b7652b-5f4c-4048-bed6-e65725e4a58f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SIvCob']/a[5]</value>
      <webElementGuid>a1d918ff-b18f-4e19-8792-3d2876701f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'தமிழ்')]</value>
      <webElementGuid>ced15b60-8862-4a24-8472-e68de68102af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='मराठी'])[1]/following::a[1]</value>
      <webElementGuid>7d056ba4-1722-4a43-a5cb-abfd38968d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='తెలుగు'])[1]/following::a[2]</value>
      <webElementGuid>b00f1524-434f-43fa-ad7e-eb59cae90b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ગુજરાતી'])[1]/preceding::a[1]</value>
      <webElementGuid>aef93cfb-87ec-47ef-af00-a677ae80a04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ಕನ್ನಡ'])[1]/preceding::a[2]</value>
      <webElementGuid>7f1a3080-76f3-46d2-bc23-062b8bca184d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='தமிழ்']/parent::*</value>
      <webElementGuid>ce0c0180-b7c8-482f-90ad-05e666a6c1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.co.in/setprefs?sig=0_limky8E0i7HQ_0Klma2ehAgaS6I%3D&amp;hl=ta&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjwms7quZuEAxWUqFYBHc6xAeIQ2ZgBCBg')]</value>
      <webElementGuid>4a09e106-5d1b-4517-8c46-26c5934717df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>cbff47b7-b9df-48c6-8293-3baaa5b6d1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.co.in/setprefs?sig=0_limky8E0i7HQ_0Klma2ehAgaS6I%3D&amp;hl=ta&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjwms7quZuEAxWUqFYBHc6xAeIQ2ZgBCBg' and (text() = 'தமிழ்' or . = 'தமிழ்')]</value>
      <webElementGuid>3d5125cd-c37a-4010-aafa-b144cb28a19e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
