<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_English</name>
   <tag></tag>
   <elementGuidId>22710742-24c8-4d77-9d20-b66285d454e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SIvCob']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SIvCob > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cadd55c0-ef1d-4a82-a580-94bd3f074891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.co.in/setprefs?sig=0_limky8E0i7HQ_0Klma2ehAgaS6I%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjZgNzruZuEAxUs1jQHHZLMBbQQ2ZgBCBQ</value>
      <webElementGuid>1ce5f0eb-ae52-45ed-8f55-68b1ef93f99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>b149354c-a626-4217-880e-e472f2d7431d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SIvCob&quot;)/a[1]</value>
      <webElementGuid>f3a1a271-5a54-4bbd-90eb-59b36fd193b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SIvCob']/a</value>
      <webElementGuid>cba0d054-d3c2-4583-92c1-df16c33c45f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'English')]</value>
      <webElementGuid>fc0567a9-0043-4ab7-a380-74160465dc1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='பொருத்தமற்ற முன்கணிப்புகளைப் புகாரளி'])[1]/following::a[1]</value>
      <webElementGuid>a5fdfe99-d407-42aa-8838-a75047e76fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='हिन्दी'])[1]/preceding::a[1]</value>
      <webElementGuid>aeb6a4bb-8bed-4d33-99c8-b81c97b337e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='বাংলা'])[1]/preceding::a[2]</value>
      <webElementGuid>4ed8293f-3c4c-4b7e-9934-bb86e6f67c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='English']/parent::*</value>
      <webElementGuid>4c183460-2bc7-4b0a-9f5f-a0ab2e7c8aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.co.in/setprefs?sig=0_limky8E0i7HQ_0Klma2ehAgaS6I%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjZgNzruZuEAxUs1jQHHZLMBbQQ2ZgBCBQ')]</value>
      <webElementGuid>b2591b27-7afe-4cad-bb28-90344b7ca4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a</value>
      <webElementGuid>43ba01d3-eae3-4139-9f61-1b39dcd0620b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.co.in/setprefs?sig=0_limky8E0i7HQ_0Klma2ehAgaS6I%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjZgNzruZuEAxUs1jQHHZLMBbQQ2ZgBCBQ' and (text() = 'English' or . = 'English')]</value>
      <webElementGuid>67056b6a-034f-4cdd-813f-a372866dde7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
