<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>English</name>
   <tag></tag>
   <elementGuidId>1de9b699-d01d-44d2-85a4-aaf409bac6ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SIvCob']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SIvCob > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d9a6cbb-4d6c-4829-b97a-de505cf592b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.co.in/setprefs?sig=0_AUN6dv8mfMWf5EFNqNHPBPBjVvc%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwj5tqq2uJuEAxUpSGwGHalLC1AQ2ZgBCBQ</value>
      <webElementGuid>e0c73ea1-8642-442d-8d4d-65e18a34b5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>c2b75d23-9751-4a8c-bd3c-b64c2bb074be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SIvCob&quot;)/a[1]</value>
      <webElementGuid>1182323f-4931-4ab0-b3ec-81b96c9b199b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SIvCob']/a</value>
      <webElementGuid>84f289ef-c0fb-4afd-a10f-591bd41e7aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'English')]</value>
      <webElementGuid>a780e079-ee6a-4e55-b35d-0f5c6f54c2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='பொருத்தமற்ற முன்கணிப்புகளைப் புகாரளி'])[1]/following::a[1]</value>
      <webElementGuid>7bfcd0e8-9f7b-4c34-9572-61ed9981b9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='हिन्दी'])[1]/preceding::a[1]</value>
      <webElementGuid>3ce1dc14-31e7-407a-964a-b0cef8224c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='বাংলা'])[1]/preceding::a[2]</value>
      <webElementGuid>ea172a5d-894d-4720-aa89-7ebaee7bff9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='English']/parent::*</value>
      <webElementGuid>55da264b-182f-4a87-a4ca-859db0198efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.co.in/setprefs?sig=0_AUN6dv8mfMWf5EFNqNHPBPBjVvc%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwj5tqq2uJuEAxUpSGwGHalLC1AQ2ZgBCBQ')]</value>
      <webElementGuid>26792c77-ca5c-4ef9-b0d3-7ff57ace1ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a</value>
      <webElementGuid>d8c8d6cc-18e9-4797-b7dc-eadc05f2f6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.co.in/setprefs?sig=0_AUN6dv8mfMWf5EFNqNHPBPBjVvc%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwj5tqq2uJuEAxUpSGwGHalLC1AQ2ZgBCBQ' and (text() = 'English' or . = 'English')]</value>
      <webElementGuid>ee6f6a88-7911-4252-b9e9-12f4efb63946</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
