<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tamil</name>
   <tag></tag>
   <elementGuidId>0af473b9-2484-4a57-ab89-e066461391bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SIvCob']/a[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(5)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5457e241-76c2-483f-b9e1-4ada3cab1ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.co.in/setprefs?sig=0_AUN6dv8mfMWf5EFNqNHPBPBjVvc%3D&amp;hl=ta&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwin-8C0uJuEAxXKffUHHSY0DmcQ2ZgBCBg</value>
      <webElementGuid>8671ec30-53c2-40fd-a5f2-3080c5b08370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>தமிழ்</value>
      <webElementGuid>92926544-7347-4267-819c-f0ef12032174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SIvCob&quot;)/a[5]</value>
      <webElementGuid>784372b9-007a-474c-ba77-1281985a6b34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SIvCob']/a[5]</value>
      <webElementGuid>bdbc9cc9-025d-41d6-95ab-7e11c4bdf881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'தமிழ்')]</value>
      <webElementGuid>98b68c4b-22a4-4999-bdfa-a85a72b94050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='मराठी'])[1]/following::a[1]</value>
      <webElementGuid>3b8d2c8d-a87a-4550-9b0b-1082acc52d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='తెలుగు'])[1]/following::a[2]</value>
      <webElementGuid>0d4cef23-9a9d-4ecf-8121-f6baec7d9c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ગુજરાતી'])[1]/preceding::a[1]</value>
      <webElementGuid>f0d4dbe7-ef9f-4518-9b74-6df067ca5e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ಕನ್ನಡ'])[1]/preceding::a[2]</value>
      <webElementGuid>d4af24cb-7d47-4bfb-8dde-611837dda706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='தமிழ்']/parent::*</value>
      <webElementGuid>c0dcfc4a-15d6-47b6-9bed-66224336688b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.co.in/setprefs?sig=0_AUN6dv8mfMWf5EFNqNHPBPBjVvc%3D&amp;hl=ta&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwin-8C0uJuEAxXKffUHHSY0DmcQ2ZgBCBg')]</value>
      <webElementGuid>268d353b-6b8d-4075-986d-f08494152969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>71b83eed-fee0-4abb-b174-10653911c2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.co.in/setprefs?sig=0_AUN6dv8mfMWf5EFNqNHPBPBjVvc%3D&amp;hl=ta&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwin-8C0uJuEAxXKffUHHSY0DmcQ2ZgBCBg' and (text() = 'தமிழ்' or . = 'தமிழ்')]</value>
      <webElementGuid>0aff98c8-dc05-4721-8d79-ff7ff98eb6c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
